// Code generated by protoc-gen-go. DO NOT EDIT.
// source: main.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Type of the domain matchment
type Domain_Type int32

const (
	Domain_FULL_MATCH Domain_Type = 0
	Domain_WILDCARD   Domain_Type = 1
)

var Domain_Type_name = map[int32]string{
	0: "FULL_MATCH",
	1: "WILDCARD",
}

var Domain_Type_value = map[string]int32{
	"FULL_MATCH": 0,
	"WILDCARD":   1,
}

func (x Domain_Type) String() string {
	return proto.EnumName(Domain_Type_name, int32(x))
}

func (Domain_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{0, 0}
}

// Type of the redirect matchment
type Redirect_Match_Type int32

const (
	Redirect_Match_FULL_MATCH Redirect_Match_Type = 0
	Redirect_Match_WILDCARD   Redirect_Match_Type = 1
)

var Redirect_Match_Type_name = map[int32]string{
	0: "FULL_MATCH",
	1: "WILDCARD",
}

var Redirect_Match_Type_value = map[string]int32{
	"FULL_MATCH": 0,
	"WILDCARD":   1,
}

func (x Redirect_Match_Type) String() string {
	return proto.EnumName(Redirect_Match_Type_name, int32(x))
}

func (Redirect_Match_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{1, 0, 0}
}

// Domain is representing a DNS Domain Name
//
// A domain is the name either full matched or wildcard matched
// to be listen to evaluated for redirect.
type Domain struct {
	// The uuid of the domain
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// The name of the domain
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// A description of the domain
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// The type of the domain matchment.
	Type Domain_Type `protobuf:"varint,4,opt,name=type,proto3,enum=proto.Domain_Type" json:"type,omitempty"`
	// Redirects to be executed for the domain
	Redirects []*Redirect `protobuf:"bytes,5,rep,name=redirects,proto3" json:"redirects,omitempty"`
	// Time this domain is created
	Created *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created,proto3" json:"created,omitempty"`
	// Time this domain has been modified
	Modified             *timestamp.Timestamp `protobuf:"bytes,7,opt,name=modified,proto3" json:"modified,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Domain) Reset()         { *m = Domain{} }
func (m *Domain) String() string { return proto.CompactTextString(m) }
func (*Domain) ProtoMessage()    {}
func (*Domain) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{0}
}

func (m *Domain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Domain.Unmarshal(m, b)
}
func (m *Domain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Domain.Marshal(b, m, deterministic)
}
func (m *Domain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Domain.Merge(m, src)
}
func (m *Domain) XXX_Size() int {
	return xxx_messageInfo_Domain.Size(m)
}
func (m *Domain) XXX_DiscardUnknown() {
	xxx_messageInfo_Domain.DiscardUnknown(m)
}

var xxx_messageInfo_Domain proto.InternalMessageInfo

func (m *Domain) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Domain) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Domain) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Domain) GetType() Domain_Type {
	if m != nil {
		return m.Type
	}
	return Domain_FULL_MATCH
}

func (m *Domain) GetRedirects() []*Redirect {
	if m != nil {
		return m.Redirects
	}
	return nil
}

func (m *Domain) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Domain) GetModified() *timestamp.Timestamp {
	if m != nil {
		return m.Modified
	}
	return nil
}

// Redirect is representing a domain redirect
//
// A redirect is specifying a matched, or wildcard matched
// redirect of a request to new destition.
type Redirect struct {
	// UUID
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Name of the redirect
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// A description of the redirect
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Match specifies the match for a redirect
	Match *Redirect_Match `protobuf:"bytes,4,opt,name=match,proto3" json:"match,omitempty"`
	// Target specifies the target of a redirect
	Target               *Redirect_Target `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Redirect) Reset()         { *m = Redirect{} }
func (m *Redirect) String() string { return proto.CompactTextString(m) }
func (*Redirect) ProtoMessage()    {}
func (*Redirect) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{1}
}

func (m *Redirect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Redirect.Unmarshal(m, b)
}
func (m *Redirect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Redirect.Marshal(b, m, deterministic)
}
func (m *Redirect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Redirect.Merge(m, src)
}
func (m *Redirect) XXX_Size() int {
	return xxx_messageInfo_Redirect.Size(m)
}
func (m *Redirect) XXX_DiscardUnknown() {
	xxx_messageInfo_Redirect.DiscardUnknown(m)
}

var xxx_messageInfo_Redirect proto.InternalMessageInfo

func (m *Redirect) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Redirect) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Redirect) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Redirect) GetMatch() *Redirect_Match {
	if m != nil {
		return m.Match
	}
	return nil
}

func (m *Redirect) GetTarget() *Redirect_Target {
	if m != nil {
		return m.Target
	}
	return nil
}

// Match specificies a url to be matched against
type Redirect_Match struct {
	// The path to be matched against.
	// Could also be "*"
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// The type of the redirect
	Type                 Redirect_Match_Type `protobuf:"varint,2,opt,name=type,proto3,enum=proto.Redirect_Match_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Redirect_Match) Reset()         { *m = Redirect_Match{} }
func (m *Redirect_Match) String() string { return proto.CompactTextString(m) }
func (*Redirect_Match) ProtoMessage()    {}
func (*Redirect_Match) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{1, 0}
}

func (m *Redirect_Match) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Redirect_Match.Unmarshal(m, b)
}
func (m *Redirect_Match) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Redirect_Match.Marshal(b, m, deterministic)
}
func (m *Redirect_Match) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Redirect_Match.Merge(m, src)
}
func (m *Redirect_Match) XXX_Size() int {
	return xxx_messageInfo_Redirect_Match.Size(m)
}
func (m *Redirect_Match) XXX_DiscardUnknown() {
	xxx_messageInfo_Redirect_Match.DiscardUnknown(m)
}

var xxx_messageInfo_Redirect_Match proto.InternalMessageInfo

func (m *Redirect_Match) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Redirect_Match) GetType() Redirect_Match_Type {
	if m != nil {
		return m.Type
	}
	return Redirect_Match_FULL_MATCH
}

// Target specificies the target to redirect to
type Redirect_Target struct {
	// Url of the target
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Transport of the parameters
	Parameters bool `protobuf:"varint,2,opt,name=parameters,proto3" json:"parameters,omitempty"`
	// HTTP status code to return
	Code                 HTTPStatusCode `protobuf:"varint,4,opt,name=code,proto3,enum=proto.HTTPStatusCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Redirect_Target) Reset()         { *m = Redirect_Target{} }
func (m *Redirect_Target) String() string { return proto.CompactTextString(m) }
func (*Redirect_Target) ProtoMessage()    {}
func (*Redirect_Target) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{1, 1}
}

func (m *Redirect_Target) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Redirect_Target.Unmarshal(m, b)
}
func (m *Redirect_Target) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Redirect_Target.Marshal(b, m, deterministic)
}
func (m *Redirect_Target) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Redirect_Target.Merge(m, src)
}
func (m *Redirect_Target) XXX_Size() int {
	return xxx_messageInfo_Redirect_Target.Size(m)
}
func (m *Redirect_Target) XXX_DiscardUnknown() {
	xxx_messageInfo_Redirect_Target.DiscardUnknown(m)
}

var xxx_messageInfo_Redirect_Target proto.InternalMessageInfo

func (m *Redirect_Target) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Redirect_Target) GetParameters() bool {
	if m != nil {
		return m.Parameters
	}
	return false
}

func (m *Redirect_Target) GetCode() HTTPStatusCode {
	if m != nil {
		return m.Code
	}
	return HTTPStatusCode_empty
}

// Request message for CreateDomain
type CreateDomainRequest struct {
	// The domain to create.
	Domain               *Domain  `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDomainRequest) Reset()         { *m = CreateDomainRequest{} }
func (m *CreateDomainRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDomainRequest) ProtoMessage()    {}
func (*CreateDomainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{2}
}

func (m *CreateDomainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDomainRequest.Unmarshal(m, b)
}
func (m *CreateDomainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDomainRequest.Marshal(b, m, deterministic)
}
func (m *CreateDomainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDomainRequest.Merge(m, src)
}
func (m *CreateDomainRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDomainRequest.Size(m)
}
func (m *CreateDomainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDomainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDomainRequest proto.InternalMessageInfo

func (m *CreateDomainRequest) GetDomain() *Domain {
	if m != nil {
		return m.Domain
	}
	return nil
}

// Response message for CreateDomain
type CreateDomainResponse struct {
	// The domain to create.
	Domain               *Domain  `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDomainResponse) Reset()         { *m = CreateDomainResponse{} }
func (m *CreateDomainResponse) String() string { return proto.CompactTextString(m) }
func (*CreateDomainResponse) ProtoMessage()    {}
func (*CreateDomainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{3}
}

func (m *CreateDomainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDomainResponse.Unmarshal(m, b)
}
func (m *CreateDomainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDomainResponse.Marshal(b, m, deterministic)
}
func (m *CreateDomainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDomainResponse.Merge(m, src)
}
func (m *CreateDomainResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDomainResponse.Size(m)
}
func (m *CreateDomainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDomainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDomainResponse proto.InternalMessageInfo

func (m *CreateDomainResponse) GetDomain() *Domain {
	if m != nil {
		return m.Domain
	}
	return nil
}

// Request message for DeleteDomain
type DeleteDomainRequest struct {
	// The domain to create.
	Domain               *Domain  `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDomainRequest) Reset()         { *m = DeleteDomainRequest{} }
func (m *DeleteDomainRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDomainRequest) ProtoMessage()    {}
func (*DeleteDomainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{4}
}

func (m *DeleteDomainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDomainRequest.Unmarshal(m, b)
}
func (m *DeleteDomainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDomainRequest.Marshal(b, m, deterministic)
}
func (m *DeleteDomainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDomainRequest.Merge(m, src)
}
func (m *DeleteDomainRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDomainRequest.Size(m)
}
func (m *DeleteDomainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDomainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDomainRequest proto.InternalMessageInfo

func (m *DeleteDomainRequest) GetDomain() *Domain {
	if m != nil {
		return m.Domain
	}
	return nil
}

// Response message for DeleteDomain
type DeleteDomainResponse struct {
	// The domain to create.
	Domain               *Domain  `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDomainResponse) Reset()         { *m = DeleteDomainResponse{} }
func (m *DeleteDomainResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteDomainResponse) ProtoMessage()    {}
func (*DeleteDomainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{5}
}

func (m *DeleteDomainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDomainResponse.Unmarshal(m, b)
}
func (m *DeleteDomainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDomainResponse.Marshal(b, m, deterministic)
}
func (m *DeleteDomainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDomainResponse.Merge(m, src)
}
func (m *DeleteDomainResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteDomainResponse.Size(m)
}
func (m *DeleteDomainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDomainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDomainResponse proto.InternalMessageInfo

func (m *DeleteDomainResponse) GetDomain() *Domain {
	if m != nil {
		return m.Domain
	}
	return nil
}

// Request message for CreateRedirect
type CreateRedirectRequest struct {
	// The domain the redirects to create for.
	Domain *Domain `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	// The redirects to create.
	Redirects            []*Redirect `protobuf:"bytes,2,rep,name=redirects,proto3" json:"redirects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateRedirectRequest) Reset()         { *m = CreateRedirectRequest{} }
func (m *CreateRedirectRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRedirectRequest) ProtoMessage()    {}
func (*CreateRedirectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{6}
}

func (m *CreateRedirectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRedirectRequest.Unmarshal(m, b)
}
func (m *CreateRedirectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRedirectRequest.Marshal(b, m, deterministic)
}
func (m *CreateRedirectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRedirectRequest.Merge(m, src)
}
func (m *CreateRedirectRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRedirectRequest.Size(m)
}
func (m *CreateRedirectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRedirectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRedirectRequest proto.InternalMessageInfo

func (m *CreateRedirectRequest) GetDomain() *Domain {
	if m != nil {
		return m.Domain
	}
	return nil
}

func (m *CreateRedirectRequest) GetRedirects() []*Redirect {
	if m != nil {
		return m.Redirects
	}
	return nil
}

// Response message for CreateRedirect
type CreateRedirectResponse struct {
	// The domain the redirects are created for.
	Domain *Domain `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	// The redirects that is created.
	Redirects            []*Redirect `protobuf:"bytes,2,rep,name=redirects,proto3" json:"redirects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateRedirectResponse) Reset()         { *m = CreateRedirectResponse{} }
func (m *CreateRedirectResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRedirectResponse) ProtoMessage()    {}
func (*CreateRedirectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{7}
}

func (m *CreateRedirectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRedirectResponse.Unmarshal(m, b)
}
func (m *CreateRedirectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRedirectResponse.Marshal(b, m, deterministic)
}
func (m *CreateRedirectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRedirectResponse.Merge(m, src)
}
func (m *CreateRedirectResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRedirectResponse.Size(m)
}
func (m *CreateRedirectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRedirectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRedirectResponse proto.InternalMessageInfo

func (m *CreateRedirectResponse) GetDomain() *Domain {
	if m != nil {
		return m.Domain
	}
	return nil
}

func (m *CreateRedirectResponse) GetRedirects() []*Redirect {
	if m != nil {
		return m.Redirects
	}
	return nil
}

// Request message for ListDomains
type ListDomainsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDomainsRequest) Reset()         { *m = ListDomainsRequest{} }
func (m *ListDomainsRequest) String() string { return proto.CompactTextString(m) }
func (*ListDomainsRequest) ProtoMessage()    {}
func (*ListDomainsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{8}
}

func (m *ListDomainsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDomainsRequest.Unmarshal(m, b)
}
func (m *ListDomainsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDomainsRequest.Marshal(b, m, deterministic)
}
func (m *ListDomainsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDomainsRequest.Merge(m, src)
}
func (m *ListDomainsRequest) XXX_Size() int {
	return xxx_messageInfo_ListDomainsRequest.Size(m)
}
func (m *ListDomainsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDomainsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListDomainsRequest proto.InternalMessageInfo

// Response message for ListDomains
type ListDomainsResponse struct {
	// The redirects that is created.
	Domains              []*Domain `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListDomainsResponse) Reset()         { *m = ListDomainsResponse{} }
func (m *ListDomainsResponse) String() string { return proto.CompactTextString(m) }
func (*ListDomainsResponse) ProtoMessage()    {}
func (*ListDomainsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{9}
}

func (m *ListDomainsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDomainsResponse.Unmarshal(m, b)
}
func (m *ListDomainsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDomainsResponse.Marshal(b, m, deterministic)
}
func (m *ListDomainsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDomainsResponse.Merge(m, src)
}
func (m *ListDomainsResponse) XXX_Size() int {
	return xxx_messageInfo_ListDomainsResponse.Size(m)
}
func (m *ListDomainsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDomainsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDomainsResponse proto.InternalMessageInfo

func (m *ListDomainsResponse) GetDomains() []*Domain {
	if m != nil {
		return m.Domains
	}
	return nil
}

// Request message for GetDomain
type GetDomainRequest struct {
	// The domain to request.
	Domain               *Domain  `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDomainRequest) Reset()         { *m = GetDomainRequest{} }
func (m *GetDomainRequest) String() string { return proto.CompactTextString(m) }
func (*GetDomainRequest) ProtoMessage()    {}
func (*GetDomainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{10}
}

func (m *GetDomainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDomainRequest.Unmarshal(m, b)
}
func (m *GetDomainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDomainRequest.Marshal(b, m, deterministic)
}
func (m *GetDomainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDomainRequest.Merge(m, src)
}
func (m *GetDomainRequest) XXX_Size() int {
	return xxx_messageInfo_GetDomainRequest.Size(m)
}
func (m *GetDomainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDomainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDomainRequest proto.InternalMessageInfo

func (m *GetDomainRequest) GetDomain() *Domain {
	if m != nil {
		return m.Domain
	}
	return nil
}

// Response message for GetDomain
type GetDomainResponse struct {
	// The domain to request.
	Domain               *Domain  `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDomainResponse) Reset()         { *m = GetDomainResponse{} }
func (m *GetDomainResponse) String() string { return proto.CompactTextString(m) }
func (*GetDomainResponse) ProtoMessage()    {}
func (*GetDomainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{11}
}

func (m *GetDomainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDomainResponse.Unmarshal(m, b)
}
func (m *GetDomainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDomainResponse.Marshal(b, m, deterministic)
}
func (m *GetDomainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDomainResponse.Merge(m, src)
}
func (m *GetDomainResponse) XXX_Size() int {
	return xxx_messageInfo_GetDomainResponse.Size(m)
}
func (m *GetDomainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDomainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDomainResponse proto.InternalMessageInfo

func (m *GetDomainResponse) GetDomain() *Domain {
	if m != nil {
		return m.Domain
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.Domain_Type", Domain_Type_name, Domain_Type_value)
	proto.RegisterEnum("proto.Redirect_Match_Type", Redirect_Match_Type_name, Redirect_Match_Type_value)
	proto.RegisterType((*Domain)(nil), "proto.Domain")
	proto.RegisterType((*Redirect)(nil), "proto.Redirect")
	proto.RegisterType((*Redirect_Match)(nil), "proto.Redirect.Match")
	proto.RegisterType((*Redirect_Target)(nil), "proto.Redirect.Target")
	proto.RegisterType((*CreateDomainRequest)(nil), "proto.CreateDomainRequest")
	proto.RegisterType((*CreateDomainResponse)(nil), "proto.CreateDomainResponse")
	proto.RegisterType((*DeleteDomainRequest)(nil), "proto.DeleteDomainRequest")
	proto.RegisterType((*DeleteDomainResponse)(nil), "proto.DeleteDomainResponse")
	proto.RegisterType((*CreateRedirectRequest)(nil), "proto.CreateRedirectRequest")
	proto.RegisterType((*CreateRedirectResponse)(nil), "proto.CreateRedirectResponse")
	proto.RegisterType((*ListDomainsRequest)(nil), "proto.ListDomainsRequest")
	proto.RegisterType((*ListDomainsResponse)(nil), "proto.ListDomainsResponse")
	proto.RegisterType((*GetDomainRequest)(nil), "proto.GetDomainRequest")
	proto.RegisterType((*GetDomainResponse)(nil), "proto.GetDomainResponse")
}

func init() { proto.RegisterFile("main.proto", fileDescriptor_7ed94b0a22d11796) }

var fileDescriptor_7ed94b0a22d11796 = []byte{
	// 625 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0xc5, 0xb9, 0xb8, 0xe9, 0xb8, 0x94, 0x30, 0xbd, 0x60, 0xcc, 0x2d, 0xb2, 0xb8, 0x04, 0x21,
	0x5c, 0xc9, 0x20, 0x24, 0x50, 0xa9, 0x54, 0x25, 0xa2, 0x45, 0x4a, 0x04, 0x5a, 0x8c, 0x78, 0x44,
	0x6e, 0xbc, 0x4d, 0x2c, 0xc5, 0xb1, 0x6b, 0xaf, 0x85, 0xfa, 0x0d, 0x7c, 0x13, 0xdf, 0xc4, 0x2f,
	0x20, 0xef, 0xae, 0x83, 0xed, 0x1a, 0xb5, 0xa9, 0x78, 0xf2, 0x7a, 0xce, 0x99, 0x39, 0xb3, 0x33,
	0x67, 0x01, 0x02, 0xd7, 0x5f, 0x58, 0x51, 0x1c, 0xb2, 0x10, 0xdb, 0xfc, 0x63, 0xc0, 0x8c, 0xb1,
	0x48, 0x84, 0x8c, 0x47, 0xd3, 0x30, 0x9c, 0xce, 0xe9, 0x1e, 0xff, 0x3b, 0x49, 0x4f, 0xf7, 0x98,
	0x1f, 0xd0, 0x84, 0xb9, 0x81, 0x24, 0x98, 0xbf, 0x1a, 0xa0, 0x0e, 0xc3, 0xac, 0x08, 0x22, 0xb4,
	0xd2, 0xd4, 0xf7, 0x74, 0xa5, 0xa7, 0xf4, 0xd7, 0x09, 0x3f, 0x67, 0xb1, 0x85, 0x1b, 0x50, 0xbd,
	0x21, 0x62, 0xd9, 0x19, 0x7b, 0xa0, 0x79, 0x34, 0x99, 0xc4, 0x7e, 0xc4, 0xfc, 0x70, 0xa1, 0x37,
	0x39, 0x54, 0x0c, 0xe1, 0x53, 0x68, 0xb1, 0xf3, 0x88, 0xea, 0xad, 0x9e, 0xd2, 0xdf, 0xb4, 0x51,
	0x48, 0x59, 0x42, 0xc6, 0x72, 0xce, 0x23, 0x4a, 0x38, 0x8e, 0x2f, 0x61, 0x3d, 0xa6, 0x9e, 0x1f,
	0xd3, 0x09, 0x4b, 0xf4, 0x76, 0xaf, 0xd9, 0xd7, 0xec, 0x5b, 0x92, 0x4c, 0x64, 0x9c, 0xfc, 0x65,
	0xe0, 0x6b, 0x58, 0x9b, 0xc4, 0xd4, 0x65, 0xd4, 0xd3, 0xd5, 0x9e, 0xd2, 0xd7, 0x6c, 0xc3, 0x12,
	0xd7, 0xb3, 0xf2, 0xeb, 0x59, 0x4e, 0x7e, 0x3d, 0x92, 0x53, 0xf1, 0x0d, 0x74, 0x82, 0xd0, 0xf3,
	0x4f, 0x7d, 0xea, 0xe9, 0x6b, 0x97, 0xa6, 0x2d, 0xb9, 0xe6, 0x63, 0x68, 0x65, 0xad, 0xe2, 0x26,
	0xc0, 0x87, 0xaf, 0xa3, 0xd1, 0xf7, 0xf1, 0xa1, 0x33, 0x38, 0xee, 0xde, 0xc0, 0x0d, 0xe8, 0x7c,
	0xfb, 0x38, 0x1a, 0x0e, 0x0e, 0xc9, 0xb0, 0xab, 0x98, 0x3f, 0x9b, 0xd0, 0xc9, 0x7b, 0xfd, 0x8f,
	0x13, 0x7c, 0x01, 0xed, 0xc0, 0x65, 0x93, 0x19, 0x1f, 0xa1, 0x66, 0xef, 0x54, 0xa6, 0x62, 0x8d,
	0x33, 0x90, 0x08, 0x0e, 0x5a, 0xa0, 0x32, 0x37, 0x9e, 0x52, 0xa6, 0xb7, 0x39, 0x7b, 0xb7, 0xca,
	0x76, 0x38, 0x4a, 0x24, 0xcb, 0x38, 0x83, 0x36, 0xcf, 0xcf, 0x7a, 0x8b, 0x5c, 0x36, 0xcb, 0xfb,
	0xcd, 0xce, 0x68, 0xc9, 0xdd, 0x35, 0xf8, 0xee, 0x8c, 0x5a, 0xe1, 0xc2, 0x0e, 0xaf, 0x36, 0x26,
	0x83, 0x82, 0x2a, 0x9a, 0xc0, 0x2e, 0x34, 0xd3, 0x78, 0x2e, 0x25, 0xb3, 0x23, 0x3e, 0x04, 0x88,
	0xdc, 0xd8, 0x0d, 0x28, 0xa3, 0x71, 0xc2, 0x75, 0x3b, 0xa4, 0x10, 0xc1, 0xe7, 0xd0, 0x9a, 0x84,
	0x5e, 0xee, 0xa6, 0x7c, 0x14, 0xc7, 0x8e, 0xf3, 0xf9, 0x0b, 0x73, 0x59, 0x9a, 0x0c, 0x42, 0x8f,
	0x12, 0x4e, 0x31, 0xf7, 0x61, 0x6b, 0xc0, 0xd7, 0x2e, 0xbc, 0x46, 0xe8, 0x59, 0x4a, 0x13, 0x86,
	0x4f, 0x40, 0xf5, 0x78, 0x80, 0xcb, 0x6a, 0xf6, 0xcd, 0x92, 0x23, 0x89, 0x04, 0xcd, 0xf7, 0xb0,
	0x5d, 0xce, 0x4e, 0xa2, 0x70, 0x91, 0xd0, 0xab, 0xa6, 0xef, 0xc3, 0xd6, 0x90, 0xce, 0xe9, 0xf5,
	0xc5, 0xcb, 0xd9, 0xab, 0x89, 0x07, 0xb0, 0x23, 0x7a, 0x5f, 0x3e, 0x9c, 0x95, 0xe4, 0xcb, 0x4f,
	0xb1, 0x71, 0xd9, 0x53, 0x34, 0x17, 0xb0, 0x5b, 0x95, 0x5b, 0xa9, 0xdf, 0x55, 0xf5, 0xb6, 0x01,
	0x47, 0x7e, 0xc2, 0x44, 0x91, 0x44, 0xde, 0xcd, 0x3c, 0x80, 0xad, 0x52, 0x54, 0xb6, 0xf0, 0x0c,
	0xd6, 0x84, 0x4a, 0xa2, 0x2b, 0xbc, 0x72, 0xa5, 0x87, 0x1c, 0x35, 0xdf, 0x42, 0xf7, 0x88, 0xb2,
	0x6b, 0xad, 0xeb, 0x1d, 0xdc, 0x2e, 0xa4, 0xae, 0x74, 0x77, 0xfb, 0x77, 0x03, 0xd4, 0x4f, 0x29,
	0x9b, 0xbb, 0x3f, 0xf0, 0x08, 0x36, 0x8a, 0x96, 0xc3, 0xfc, 0xbd, 0xd5, 0xb8, 0xd8, 0xb8, 0x57,
	0x8b, 0x49, 0xe9, 0x23, 0xd8, 0x28, 0xda, 0x67, 0x59, 0xa8, 0xc6, 0x91, 0xcb, 0x42, 0xb5, 0x7e,
	0x1b, 0xc3, 0x66, 0x79, 0xb3, 0x78, 0xbf, 0xa4, 0x5b, 0xf1, 0x97, 0xf1, 0xe0, 0x1f, 0xa8, 0x2c,
	0x77, 0x00, 0xeb, 0xcb, 0x39, 0xe1, 0x1d, 0xc9, 0xad, 0x0e, 0xdd, 0xd0, 0x2f, 0x02, 0x32, 0x7f,
	0x08, 0x5a, 0x61, 0xc5, 0x78, 0x57, 0x12, 0x2f, 0x9a, 0xc1, 0x30, 0xea, 0x20, 0x51, 0xe5, 0x44,
	0xe5, 0xd0, 0xab, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf4, 0x75, 0xe4, 0x2d, 0x2e, 0x07, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OutlawClient is the client API for Outlaw service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OutlawClient interface {
	// CreateDomain is creating a new domain.
	CreateDomain(ctx context.Context, in *CreateDomainRequest, opts ...grpc.CallOption) (*CreateDomainResponse, error)
	// DeleteDomain is deleting a domain.
	DeleteDomain(ctx context.Context, in *DeleteDomainRequest, opts ...grpc.CallOption) (*DeleteDomainResponse, error)
	// Create Redirect
	CreateRedirect(ctx context.Context, in *CreateRedirectRequest, opts ...grpc.CallOption) (*CreateRedirectResponse, error)
	// GetDomain is fetching a domain.
	GetDomain(ctx context.Context, in *GetDomainRequest, opts ...grpc.CallOption) (*GetDomainResponse, error)
	// ListDomains is listing domains.
	ListDomains(ctx context.Context, in *ListDomainsRequest, opts ...grpc.CallOption) (*ListDomainsResponse, error)
}

type outlawClient struct {
	cc *grpc.ClientConn
}

func NewOutlawClient(cc *grpc.ClientConn) OutlawClient {
	return &outlawClient{cc}
}

func (c *outlawClient) CreateDomain(ctx context.Context, in *CreateDomainRequest, opts ...grpc.CallOption) (*CreateDomainResponse, error) {
	out := new(CreateDomainResponse)
	err := c.cc.Invoke(ctx, "/proto.Outlaw/CreateDomain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outlawClient) DeleteDomain(ctx context.Context, in *DeleteDomainRequest, opts ...grpc.CallOption) (*DeleteDomainResponse, error) {
	out := new(DeleteDomainResponse)
	err := c.cc.Invoke(ctx, "/proto.Outlaw/DeleteDomain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outlawClient) CreateRedirect(ctx context.Context, in *CreateRedirectRequest, opts ...grpc.CallOption) (*CreateRedirectResponse, error) {
	out := new(CreateRedirectResponse)
	err := c.cc.Invoke(ctx, "/proto.Outlaw/CreateRedirect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outlawClient) GetDomain(ctx context.Context, in *GetDomainRequest, opts ...grpc.CallOption) (*GetDomainResponse, error) {
	out := new(GetDomainResponse)
	err := c.cc.Invoke(ctx, "/proto.Outlaw/GetDomain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outlawClient) ListDomains(ctx context.Context, in *ListDomainsRequest, opts ...grpc.CallOption) (*ListDomainsResponse, error) {
	out := new(ListDomainsResponse)
	err := c.cc.Invoke(ctx, "/proto.Outlaw/ListDomains", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OutlawServer is the server API for Outlaw service.
type OutlawServer interface {
	// CreateDomain is creating a new domain.
	CreateDomain(context.Context, *CreateDomainRequest) (*CreateDomainResponse, error)
	// DeleteDomain is deleting a domain.
	DeleteDomain(context.Context, *DeleteDomainRequest) (*DeleteDomainResponse, error)
	// Create Redirect
	CreateRedirect(context.Context, *CreateRedirectRequest) (*CreateRedirectResponse, error)
	// GetDomain is fetching a domain.
	GetDomain(context.Context, *GetDomainRequest) (*GetDomainResponse, error)
	// ListDomains is listing domains.
	ListDomains(context.Context, *ListDomainsRequest) (*ListDomainsResponse, error)
}

func RegisterOutlawServer(s *grpc.Server, srv OutlawServer) {
	s.RegisterService(&_Outlaw_serviceDesc, srv)
}

func _Outlaw_CreateDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutlawServer).CreateDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Outlaw/CreateDomain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutlawServer).CreateDomain(ctx, req.(*CreateDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Outlaw_DeleteDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutlawServer).DeleteDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Outlaw/DeleteDomain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutlawServer).DeleteDomain(ctx, req.(*DeleteDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Outlaw_CreateRedirect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRedirectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutlawServer).CreateRedirect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Outlaw/CreateRedirect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutlawServer).CreateRedirect(ctx, req.(*CreateRedirectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Outlaw_GetDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutlawServer).GetDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Outlaw/GetDomain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutlawServer).GetDomain(ctx, req.(*GetDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Outlaw_ListDomains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDomainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutlawServer).ListDomains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Outlaw/ListDomains",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutlawServer).ListDomains(ctx, req.(*ListDomainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Outlaw_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Outlaw",
	HandlerType: (*OutlawServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDomain",
			Handler:    _Outlaw_CreateDomain_Handler,
		},
		{
			MethodName: "DeleteDomain",
			Handler:    _Outlaw_DeleteDomain_Handler,
		},
		{
			MethodName: "CreateRedirect",
			Handler:    _Outlaw_CreateRedirect_Handler,
		},
		{
			MethodName: "GetDomain",
			Handler:    _Outlaw_GetDomain_Handler,
		},
		{
			MethodName: "ListDomains",
			Handler:    _Outlaw_ListDomains_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "main.proto",
}
